import = [ "~/.config/alacritty/themes/everforest.toml" ]
live_config_reload = true

[window.padding]
x = 5
y = 5

[font]
size = 18

[font.bold]
family = "BitstromWera Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "BitstromWera Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "BitstromWera Nerd Font Mono"
style = "Italic"

[font.normal]
family = "BitstromWera Nerd Font Mono"

